---
version: '2'
services:
  zeek-streamer:
    image: bertisondocker/zeek-tcpreplay-kafka:latest
    container_name: zeek-streamer
    depends_on:
      - broker
    hostname: zeek-streamer
    entrypoint: /init_dummy.sh
    volumes:
      - ./pcaps:/pcaps
      - ./local.zeek:/usr/local/zeek/share/zeek/site/local.zeek
      - ./send-to-kafka.zeek:/usr/local/zeek/share/zeek/site/send-to-kafka.zeek
    cap_add: 
      - NET_ADMIN
